algoritmo "Logica"
var
   num1,num2, subtracao, resultado1 : inteiro
inicio
    escreva (" digite um numero:")
    leia (num1)
    escreva (" digite outro numero: ")
    leia (num2)
    escreval ("o resultado dessa soma é = ", num1+num2)
    escreva ("digite outro numero para subtrair: ")
    leia (resultado1)
    escreva ("o resultado desses numeros é: ", num1+num2-resultado1)
    
fimalgoritmo